@startuml JournalProgram

Class JProgram
{
    +Main() : void
}

Class Journal
{
- _entries : List <Entry>
--
+ LoadFromFile(filename) : void
+ SaveToFile(filename) : void
+ DeleteEntry(EntryIndex) : void
+ DisplayEntries() : void
+ AddEntries(entry) : void
}

class Entry
{
-_response : string
-_date : int
-_prompt : string
--
+Display(int date, string prompt, string response) : void
+Entry () : void
+GetPrompt() : string
+GetResponse() : void
}

class PromptGen
{
-_prompt : string
-_random : Random
--
+GetPrompt() : string
}

class Menu
{
--
+Write() : void
+Display() : void
+Load() : void
+Save() : void
+Delete() : void
+Quit() : void
}

Journal -* Entry
Entry -* PromptGen
Menu -> PromptGen
Menu -> Entry
Menu -> Journal


@enduml