@startuml

class Program
{
    --
    + Main()
}

class Menu
{
    -_menuChoice : int
    --
    + DisplayMenu() : void
    + ReadMenu() : void

}

class Activity
{
    -_random : Random
    -_introMessage
    -_closingMessage
    --
    + DisplayIntroMessage() : void
    + DisplayClosingMessage() : void
    + Runtime(time : int) : void
    + GetName(name) : string
    + GetDescription(description) : string
    + SetName() : void
}

class Breathing
{
    -_activityName
    -_activityDescription
    --
    Breathing(activityName : string, activityDescription : string)
}

class Reflection
{
    -_activityName
    -_activityDescription
    --

}

class Listening
{
    -_activityName
    -_activityDescription
    --
    
}




@enduml